title: Eric Farish
logo: /assets/img/me4.jpg
description: Machine Learning Portfolio
#show_downloads: true
theme: jekyll-theme-minimal
format:
  html:
    grid:
      sidebar-width: 50px
sidebar:
  - name: LinkedIn
    link: https://www.linkedin.com/in/eric-farish-ba86692
